
Adjective Expressions: [
  [Word(closed)],
  [Word(open)],
  [Word(closed), Word(under), Word(finite), Word(unions)],
  [Word(infinite)],
  [Word(finite)],
  [Word(equinumerous), Word(to), Variable],
  [Word(selfinverse)],
  [Word(involutory)],
  [Word(invertible)],
  [Word(injective)],
  [Word(surjective), Word(onto), Variable],
  [Word(inductive), Word(regarding), Variable, Word(and), Variable],
  [Word(prime), Word(to), Variable],
  [Word(mutually), Word(), Variable, Word(prime)],
  [Word(relatively), Word(), Variable, Word(prime)],
  [Word(coprime), Word(), Variable],
  [Word(compound)],
  [Word(prime)],
  [Word(congruent), Word(), Variable, Word(modulo), Variable],
  [Word(composite)],
  [Word(divisible), Word(by), Variable],
  [Word(greater), Word(than), Word(or), Word(equal), Word(to), Variable],
  [Word(less), Word(than), Word(or), Word(equal), Word(to), Variable],
  [Word(positive)],
  [Word(greater), Word(than), Variable],
  [Word(less), Word(than), Variable],
  [Word(nonzero)],
  [Word(disjoint), Word(), Variable],
  [Word(nonempty)],
  [Word(empty)],
  [Word(included), Word(in), Variable],
  [Word(defined), Word(on), Variable],
  [Word(distinct), Word(), Variable],
  [Word(in), Variable],
  [Word(contained), Word(in), Variable],
  [Word(equal), Word(to), Variable],
  [Word(nonequal), Word(to), Variable],
  [Word(inductively), Word(less), Word(than), Variable]
]

Verb Expressions: [
  [Word(has), Variable, Word(elements, element)],
  [Word(surjects, surject), Word(onto), Variable],
  [Word(divides, divide), Variable],
  [Word(agrees, agree), Word(with), Variable],
  [Word(agree, agrees), Word(), Variable],
  [Word(lies, lie), Word(in), Variable],
  [Word(contains, contain), Variable],
  [Word(belongs, belong), Word(to), Variable]
]

Notion Expressions: [
  [Word(system, systems), Word(of), Word(closed), Word(sets), Name],
  [Word(system, systems), Word(of), Word(open), Word(sets), Name],
  [Word(complement), Name, Word(of), Variable],
  [Word(involution, involutions), Name, Word(on), Variable],
  [Word(inverse, inverses), Name, Word(of), Variable],
  [Word(permutation, permutations), Name, Word(of), Variable],
  [Word(bijection, bijections), Name, Word(from), Variable, Word(to), Variable],
  [Word(bijection, bijections), Name, Word(between), Variable, Word(and), Variable],
  [Word(surjective), Word(map, maps), Name, Word(from), Variable, Word(onto), Variable],
  [Word(surjective), Word(map, maps), Name, Word(from), Variable, Word(to), Variable],
  [Word(surjective), Word(map, maps), Name, Word(onto), Variable],
  [Word(direct), Word(product, products), Name, Word(of), Variable, Word(and), Variable],
  [Word(cartesian), Word(product, products), Name, Word(of), Variable, Word(and), Variable],
  [Word(ordered), Word(pair, pairs), Name],
  [Word(pair, pairs), Name],
  [Word(choice), Word(map, maps), Name, Word(for), Variable],
  [Word(powerset), Name, Word(of), Variable],
  [Word(intersection), Name, Word(over), Variable],
  [Word(system, systems), Word(of), Word(subsets, subset), Name, Word(of), Variable],
  [Word(system, systems), Word(of), Word(nonempty), Word(sets), Name],
  [Word(system, systems), Word(of), Word(sets), Name],
  [Word(singleton), Word(set), Name],
  [Word(singleton), Word(set), Name, Word(of), Variable],
  [Word(powerclass), Name, Word(of), Variable],
  [Word(proper), Word(superset, supersets), Name, Word(of), Variable],
  [Word(proper), Word(subset, subsets), Name, Word(of), Variable],
  [Word(superset, supersets), Name, Word(of), Variable],
  [Word(subset, subsets), Name, Word(of), Variable],
  [Word(fixed), Word(point), Name, Word(of), Variable],
  [Word(function, functions), Name, Word(on), Variable],
  [Word(map, maps), Name, Word(on), Variable],
  [Word(function, functions), Name, Word(from), Variable, Word(to), Variable],
  [Word(map, maps), Name, Word(from), Variable, Word(to), Variable],
  [Word(function, functions), Name, Word(to), Variable],
  [Word(map, maps), Name, Word(to), Variable],
  [Word(function, functions), Name, Word(of), Variable],
  [Word(map, maps), Name, Word(of), Variable],
  [Word(inverse, inverses), Word(image), Name, Word(of), Variable, Word(under), Variable],
  [Word(preimage), Name, Word(of), Variable, Word(under), Variable],
  [Word(direct), Word(image), Name, Word(of), Variable, Word(under), Variable],
  [Word(image), Name, Word(of), Variable, Word(under), Variable],
  [Word(restriction), Name, Word(of), Variable, Word(to), Variable],
  [Word(composition), Name, Word(of), Variable, Word(and), Variable],
  [Word(identity), Word(map, maps), Name, Word(on), Variable],
  [Word(range), Name, Word(of), Variable],
  [Word(value, values), Name, Word(of), Variable],
  [Word(prime), Word(number, numbers), Name],
  [Word(difference), Name, Word(of), Variable, Word(and), Variable],
  [Word(remainder), Name, Word(of), Variable, Word(over), Variable],
  [Word(quotient, quotients), Name, Word(of), Variable, Word(over), Variable],
  [Word(nontrivial), Word(divisor, divisors), Name, Word(of), Variable],
  [Word(trivial), Word(divisor, divisors), Name, Word(of), Variable],
  [Word(divisor, divisors), Name, Word(of), Variable],
  [Word(factor, factors), Name, Word(of), Variable],
  [Word(successor, successors), Name, Word(of), Variable],
  [Word(predecessor, predecessors), Name, Word(of), Variable],
  [Word(product, products), Name, Word(of), Variable, Word(and), Variable],
  [Word(direct), Word(successor, successors), Name, Word(of), Variable],
  [Word(sum), Name, Word(of), Variable, Word(and), Variable],
  [Word(natural), Word(number, numbers), Name],
  [Word(complement), Name, Word(of), Variable, Word(in), Variable],
  [Word(intersection), Name, Word(of), Variable, Word(and), Variable],
  [Word(union), Name, Word(of), Variable, Word(and), Variable],
  [Word(unique), Word(element, elements), Name, Word(of), Variable],
  [Word(singleton), Word(class, classes), Name],
  [Word(singleton), Word(class, classes), Name, Word(of), Variable],
  [Word(unordered), Word(pair, pairs), Name],
  [Word(unordered), Word(pair, pairs), Name, Word(of), Variable, Word(and), Variable],
  [Word(proper), Word(superclass, superclasses), Name, Word(of), Variable],
  [Word(proper), Word(subclass, subclasses), Name, Word(of), Variable],
  [Word(superclass, superclasses), Name, Word(of), Variable],
  [Word(subclass, subclasses), Name, Word(of), Variable],
  [Word(value, values), Name, Word(of), Variable, Word(at), Variable],
  [Word(domain), Name, Word(of), Variable],
  [Word(ordered), Word(pair, pairs), Name],
  [Word(ordered), Word(pair, pairs), Name, Word(of), Variable, Word(and), Variable],
  [Word(member, members), Name, Word(of), Variable],
  [Word(map, maps), Name],
  [Word(function, functions), Name],
  [Word(set, sets), Name],
  [Word(class, classes, collection, collections), Name],
  [Word(object, objects, element, elements), Name],
  [Word(mathematical), Word(object, objects), Name],
  [Word(element, elements), Name, Word(of), Variable],
  [Word(value), Word(of), Variable, Word(under), Variable],
  [Word(domain), Word(of), Variable],
  [Word(ordered), Word(pair), Word(of), Variable, Word(and), Variable]
]

Symbolic Notion Expressions: [
  [Symbol(\FUNfrominto), Symbol({), Variable, Symbol(}), Symbol({), Variable, Symbol(})],
  [Symbol(\FUNfromonto), Symbol({), Variable, Symbol(}), Symbol({), Variable, Symbol(})],
  [Symbol(\FUNfromto), Symbol({), Variable, Symbol(}), Symbol({), Variable, Symbol(})],
  [Symbol(\SETstrictniclude), Variable],
  [Symbol(\SETstrictinclude), Variable],
  [Symbol(\SETniclude), Variable],
  [Symbol(\SETinclude), Variable],
  [Symbol(\Eq), Variable],
  [Symbol(\Elem), Variable]
]

Circumfix Function Expressions: [
  [Symbol(\PrimeSeq)],
  [Symbol(\ArithSeq), Symbol({), Variable, Symbol(}), Symbol({), Variable, Symbol(})],
  [Symbol(\compl), Symbol({), Variable, Symbol(})],
  [Symbol(\NATsegment), Symbol({), Variable, Symbol(}), Symbol({), Variable, Symbol(})],
  [Symbol(\FUNinv), Symbol({), Variable, Symbol(})],
  [Symbol(\SETpow), Symbol((), Variable, Symbol())],
  [Symbol(\FUNfunspace), Symbol({), Variable, Symbol(}), Symbol({), Variable, Symbol(})],
  [Symbol(\FUNpreim), Symbol({), Variable, Symbol(}), Symbol({), Variable, Symbol(})],
  [Symbol(\FUNim), Symbol({), Variable, Symbol(}), Symbol({), Variable, Symbol(})],
  [Symbol(\FUNid), Symbol({), Variable, Symbol(})],
  [Symbol(\FUNrange), Symbol((), Variable, Symbol())],
  [Symbol(\Prime)],
  [Symbol(\Natgeqthan), Symbol({), Variable, Symbol(})],
  [Symbol(\Natleqthan), Symbol({), Variable, Symbol(})],
  [Symbol(\Natgtrthan), Symbol({), Variable, Symbol(})],
  [Symbol(\Natlessthan), Symbol({), Variable, Symbol(})],
  [Symbol(nine)],
  [Symbol(\NATnine)],
  [Symbol(eight)],
  [Symbol(\NATeight)],
  [Symbol(seven)],
  [Symbol(\NATseven)],
  [Symbol(six)],
  [Symbol(\NATsix)],
  [Symbol(five)],
  [Symbol(\NATfive)],
  [Symbol(four)],
  [Symbol(\NATfour)],
  [Symbol(three)],
  [Symbol(\NATthree)],
  [Symbol(two)],
  [Symbol(\NATtwo)],
  [Symbol(one)],
  [Symbol(\NATone)],
  [Symbol(zero)],
  [Symbol(\NATzero)],
  [Symbol(\Nat)],
  [Symbol(\SETsingleton), Symbol({), Variable, Symbol(})],
  [Symbol(\SETpair), Symbol({), Variable, Symbol(}), Symbol({), Variable, Symbol(})],
  [Symbol(\SETempty)],
  [Symbol(\Dom), Symbol((), Variable, Symbol())],
  [Symbol((), Variable, Symbol(,), Variable, Symbol())]
]

Right Function Expressions: [
  [Symbol((), Variable, Symbol(,), Variable, Symbol())],
  [Symbol((), Variable, Symbol())]
]

Left Function Expressions: [
  [Symbol(\SETintersectover)],
  [Symbol(union), Symbol(over)],
  [Symbol(\SETunionover)]
]

Infix Function Expressions: [
  [Symbol(\SETprod)],
  [Symbol(\FUNrest)],
  [Symbol(\FUNcomp)],
  [Symbol(\NATsub)],
  [Symbol(\NATmod)],
  [Symbol(\NATdiv)],
  [Symbol(\NATmul)],
  [Symbol(\NATplus)],
  [Symbol(\SETdiff)],
  [Symbol(\SETintersect)],
  [Symbol(\SETunion)]
]

Circumfix Predicate Expressions: [
  [Symbol(\NATcong), Symbol({), Variable, Symbol(}), Symbol({), Variable, Symbol(}), Symbol({), Variable, Symbol(})]
]

Right Predicate Expressions: [
  [Symbol(\FUNfrominto), Symbol({), Variable, Symbol(}), Symbol({), Variable, Symbol(})],
  [Symbol(\FUNfromonto), Symbol({), Variable, Symbol(}), Symbol({), Variable, Symbol(})],
  [Symbol(\FUNfromto), Symbol({), Variable, Symbol(}), Symbol({), Variable, Symbol(})]
]

Left Predicate Expressions: [

]

Infix Predicate Expressions: [
  [Symbol(\NATnmid)],
  [Symbol(\NATmid)],
  [Symbol(\NATngeq)],
  [Symbol(\NATnleq)],
  [Symbol(\NATgeq)],
  [Symbol(\NATleq)],
  [Symbol(\NATngtr)],
  [Symbol(\NATnless)],
  [Symbol(\NATgtr)],
  [Symbol(\NATless)],
  [Symbol(includes)],
  [Symbol(\SETstrictniclude)],
  [Symbol(\SETstrictinclude)],
  [Symbol(\SETniclude)],
  [Symbol(\SETinclude)],
  [Symbol(\Eq)],
  [Symbol(\NotEq)],
  [Symbol(\ILess)],
  [Symbol(\Elem)],
  [Symbol(\NotElem)]
]

